version: '3.8'

services:
  web:
    # 現在のディレクトリにあるDockerfileを使ってイメージをビルド
    build:
      context: .
      dockerfile: Dockerfile
    # ホストのポート3000をコンテナのポート3000にマッピング
    ports:
      - "3000:3000"
    # ホストの現在のディレクトリをコンテナ内の/appにマウント（開発用）
    # これにより、ホスト側でコードを変更するとコンテナ内にも反映されます
    volumes:
      - .:/app
      # node_modulesはコンテナ内でインストールされたものを使う
      # ホストのnode_modulesがマウントされるのを防ぎます
      - /app/node_modules
    # 環境変数の設定（開発環境であることを指定）
    environment:
      NODE_ENV: development
    # コンテナ起動時に実行するコマンド
    # package.jsonで定義されている'start'スクリプトを実行
    command: npm start
